### PR TITLE
Added Van der Waals radii

### PR DESCRIPTION
**Pull request by herbertludowieg**
Added Van der Waals radii to isotopes.json file and added code to reflect changes in this file on all calls to it.

### CODE REVIEW

**Comment by avmarchenko** [comment]
This looks good. For backwards compatibility, I would probably maintain a default ```.radius``` on ```Element```s. For example,

```
class Element:
    ...
    @property
    def radius(self):
        return self.cov_radius # (or other radius)
```

**Comment by herbertludowieg** [comment]
Thank you Alex I will definitely keep that in mind for the future. I have never really used it, but now I understand why its a good idea.

**Comment by avmarchenko** [comment]
Hey you can update your PR by committing to the branch from which you made this PR. Should be a quick addition. Can you do this please?

**Comment by tjduigna** [comment]
How come travis isn't building this PR?

**Pull request merged**
